function onCreate() 
addLuaScript('scripts/pause')
addLuaScript('scripts/HEALTH_BAR_SHIT')
addLuaScript('scripts/Combo')
addLuaScript('scripts/freeplay')
addLuaScript('scripts/freeplay1')
addLuaScript('scripts/freeplay2')
addLuaScript('scripts/freeplay3')
addLuaScript('scripts/freeplay4')
addLuaScript('scripts/freeplay5')
end